baseURL = "http://knokmki612.github.io/hugo-fill-and-stroke/"
languageCode = "en-US"
title = "Fill and Stroke"
copyright = "2021 knokmki612"
theme = ["fill-and-stroke"]
defaultContentLanguage = "en"


[params]
description = "A simple site, for example"

[taxonomies]
tag = "tags"
archive = "archives"
