name = "Fill and Stroke"
license = "GPLv3"
licenselink = "https://github.com/knokmki612/hugo-fill-and-stroke/blob/master/LICENSE"
description = "A simple design, for blog"
homepage = "https://github.com/knokmki612/hugo-fill-and-stroke/"
tags = ["blog"]
min_version = "0.78.1"

[author]
  name = "knokmki612"
  homepage = "https://kuno.kdns.info/"
